[project]
name = "jaxstuff"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "arviz>=0.23.1",
    "blackjax>=1.3",
    "jax>=0.8.1",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "pandas>=2.3.3",
    "scikit-learn>=1.8.0",
    "seaborn>=0.13.2",
]
